apiVersion: v1
kind: Service
metadata:
    name: {{.Values.api_manage_customer.service.name}}
    namespace: {{.Release.Namespace}}
spec:
    type: {{.Values.api_manage_customer.service.type}}
    selector:
        app: {{.Values.api_manage_customer.deployment.name}}
    ports:
        - port: {{.Values.api_manage_customer.service.port}}
          protocol: TCP
          targetPort: {{.Values.api_manage_customer.service.targetPort}}